### ISSUE TITLE
SendingTimeAccuracy reject on market data session

### ISSUE THREAD

**Issue by jheusser** [jvirtanen/philadelphia#3]
I observed that on a market data-only session the exchange eventually sends a Reject(3) "SendingTimeAccuracy error" because the timestamp is never updated (no trades sent where there would be a good chance of updating the timestamp and heartbeat/testreq does not update timestamp). 

Do you envision the library to take care of this or would you expect the user to call `updateCurrentTimestamp` in logic outside the library?

**Comment by jvirtanen** [comment]
Yes, the intention is that the application invokes `updateTimestamp` periodically. This is to avoid the cost of timestamp formatting on `send`. The application can then use the formatted timestamp (`getCurrentTimestamp`) for other fields, such as TransactTime(60), as well.

**Comment by jheusser** [comment]
Ok, makes sense.
